baseURL = "http://sxy91.com/"
languageCode = "en"
title = "本草洋葱"
theme = "nuo"
#代码高亮
PygmentsCodeFences = true
#不使用/切割url，而使用filename.html
canonifyurls = true

# Disqus Username
#disqusShortname = "disqus_shortname"

# Google Analytics UA number
#googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
#copyright = " "

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "作品"
  weight = 20
  identifier = "works"
  url = "https://github.com/smile365"

[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "宋学彦"
  avatar = "/img/avatar.jpg"
  seotitle = "本草洋葱"
  subtitle = "我有故事，你有洋葱吗"
  description = "宋学彦的博客"
  paginate = 10

  # Choose your social networks
  email = "sxy91@qq.com"
  github = "smile365"
  #twitter = "twitter_username"
  #linkedin = "linkedin_username"
  weibo = "sxy03"
  wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  facebook = "smle365"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  zhihu = "sxy91"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Changyan Comments (China Only)
  changyan = true
  changyanId = "cytHq4Tdr"
  changyanConf = "prod_9ff410ee73431423ab6260fc7eb71b38"

  # Google Webmaster
  # https://www.google.com/webmasters/
  #googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  #msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  baiduSiteVerification = "aoDfhvdSoh"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  baiduTongji = "c72e82fc9139bd96d22ed8e902230200"

  # ICP Number (China Only)
  ICP = "京ICP备17046504号"
